// FIXME CNTR is missing from this list.
export const FIELD_TYPES = {
    BUTTON: "ACT",
    DROPDOWN: "SEL",
    LIST: "LIST",
    NUMBER: "NUM",
    PARA: "PARA",
    TEXT: "TXT",
    RAD: "RAD",
    DATE: "DATE",
    SLDR: "SLDR",
    CBX: "CBX",
    COMP: "COMP",
    LOOP_SET: "LP_SET",
    LOOP_VALUE: "LP_VAL",
    LOOP_INDEX: "LP_IND",
    LOOP_SIZE: "LP_SIZE",
    FILE: "FILE",
    DOC: "DOC",
    USERPICKER: "USER",
    DOCUSIGN_STATUS: "DOCUSIGN_STATUS",
    TXT: "TXT",
    NUM: "NUM",
};
